name: My First Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello from GitHub Act"
      - run: ls -la
      - run: echo "Repo is on branch $GITHUB_REF_NAME"
